name: PHPCS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHPCS
      uses: domw/phpcs@master
      run: phpcs --colors --standard=Magento2 --report=full,summary,gitblame ./
